//lookup dictionary for the type of the member and getting the icon
var iconDict =
{
  "Fox":
  {
    "url":"SVG/Fox.svg",
    "Length":100,
    "Width":150
  },
  "Bird":
  {
    "url":"SVG/Bird.svg",
    "Length":100,
    "Width":150
  },
  "Person":
  {
    "url":"SVG/Person.svg",
    "Length":250,
    "Width":150
  },
  "House":
  {
    "url":"SVG/House.svg",
    "Length":200,
    "Width":250
  },
  "GrassLand":
  {
    "url":"SVG/Green.svg",
    "Length":200,
    "Width":150
  }
};
